### ISSUE TITLE
Caporal not working with esModuleInterop

### ISSUE THREAD

**Issue by graphcon** [mattallty/Caporal.js#171]
**Describe the bug**
When you activate `esModuleInterop` in `tsconfig.json`, caporal doesn't work, giving the exception 
```
prog.parse(process.argv);
     ^

TypeError: prog.parse is not a function
    at Object.<anonymous> (D:\Sources\Node.js\caporal\dist\test.js:27:6)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
```

**To Reproduce**

1. `yarn add typescript`
2. `yarn add caporal`
3. add file `tsconfig.json` (see attachments)
4. add file `test.ts` (see attachments)
5. `yarn tsc`
6. `node dist\test.js`

Set `esModuleInterop` to `false` in `tsconfig.json` and rebuild. No exception occurs.

**Expected behavior**
That exception never occurs

**Environment informations (please complete the following information):**
 - OS: Windows
 - OS version: 1909
 - Shell: cmd.exe
 - Caporal version: 1.3.0

**Additional context**
[esModuleInterop-error.zip](https://github.com/mattallty/Caporal.js/files/4383190/esModuleInterop-error.zip)

**Comment by graphcon** [comment]
Thanks to a friend, we found out the problem is in typescript file `test.ts`, which is actually your example.

Instead of
```
import * as prog from 'caporal';
```

it's supposed to be

```
 import prog from 'caporal';
```
